name: miniCRM

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: new_crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: "postgresql://admin:admin123@postgres:5432/new_crm?sslmode=disable"
      JWT_SECRET: your_jwt_secret_here
      JWT_EXPIRES_IN: 1d
      PORT: 8080
      REDIS_URL: redis://redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - ../backend:/app
      - /app/node_modules

volumes:
  postgres_data:
