name: Deploy Backend to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/azure-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd backend
        npm ci
        
    - name: Build application
      run: |
        cd backend
        npm run build
        
    - name: Create deployment package
      run: |
        cd backend
        # Include only necessary files for production
        mkdir deploy-package
        cp -r dist node_modules package.json package-lock.json deploy-package/
        cp -r prisma deploy-package/
        cp -r generated deploy-package/
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mini-crm'
        package: ./backend/deploy-package